# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - inkFinder

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PORT : 5000
  MONGO_URL : mongodb+srv://admin:M2YZPZUns5eNcyS@cluster0.fqtchuh.mongodb.net/be?retryWrites=true&w=majority
  JWT_ACCESS_SECRET : accesssecret
  JWT_REFRESH_SECRET : refreshsecret
  SMTP_HOST : smtp.gmail.com
  SMTP_PORT : 587
  SMTP_USER : guysikme@gmail.com
  SMTP_PASSWORD : xfxwepcbfdnxjibf
  API_URL : http://localhost:5000
  CLIENT_URL : http://localhost:5000

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          npm run start

      - name: npm run start
        run: |
          npm run start
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'inkFinder'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4ACE031D129F45B18D1C71425689F764 }}
          package: .
